### ISSUE TITLE
Neon Support

### ISSUE THREAD

**Issue by wimjongman** [jantje/arduino-eclipse-plugin#484]
Provide neon support for Sloeber.

**Comment by jantje** [comment]
That is quick :-)

**Comment by wimjongman** [comment]
All good things arrive quickly.

**Comment by compihu** [comment]
Plugin cannot be installed to Neon from the nightly update site at the moment:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Arduino Eclipse Extensions 3.0.0.201606260209 (it.baeyens.arduino.feature.feature.group 3.0.0.201606260209)
  Missing requirement: Common 3.0.0.201606260209 (it.baeyens.arduino.common 3.0.0.201606260209) requires 'bundle org.eclipse.wb.core.lib 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Arduino Eclipse Extensions 3.0.0.201606260209 (it.baeyens.arduino.feature.feature.group 3.0.0.201606260209)
    To: it.baeyens.arduino.common [3.0.0.201606260209]

**Comment by jantje** [comment]
tested this here on windows 64 bit. 
I have the same problem.

**Comment by jantje** [comment]
The product states it is eclipse 4.5 which is Mars and not neon.

**Comment by compihu** [comment]
Thanks Jantje, Is there a way to keep the nightly installable in Neon release? (current ubuntu LTS is incompatible with Mars)

**Comment by wimjongman** [comment]
Good work requires time.. ;)

> It can be that the build script uses neon explicitly

Windowbuilder is no longer part of the release train. I will remove it from the requirements if possible.

**Comment by jantje** [comment]
@compihu 
as you see Wim is far better at this than I am :-)
Thanks Wim

**Comment by wimjongman** [comment]
You're welcome. Neon should now be the default. Please test the product and the update site once available.

**Comment by jantje** [comment]
I will :-)

**Comment by jantje** [comment]
You can now install the plugin in neon :-)
The product is still mars but I think this is because jenkins asked to build mars. Changed that so well see next build.

**Comment by compihu** [comment]
Thank you.

**Comment by jantje** [comment]
I ran a special build. The nightly is now neon to :-)
